zmodload zsh/zprof
ZSH_THEME="wezm"
plugins=(git docker)

export DOTFILE=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
export GOPATH=$HOME/go
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH=$GOPATH/bin:$PATH
export PATH=$PATH:/Users/giangle/.cargo/bin
source $ZSH/oh-my-zsh.sh

for f in $DOTFILE/scripts/*.sh; do source $f; done

export PATH="/opt/homebrew/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export PATH="/opt/homebrew/opt/icu4c/bin:$PATH"
export PATH="/opt/homebrew/opt/icu4c/sbin:$PATH"
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
export CLOUDSDK_PYTHON=python3

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/giangle/.gcloud/path.zsh.inc' ]; then . '/Users/giangle/.gcloud/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/giangle/.gcloud/completion.zsh.inc' ]; then . '/Users/giangle/.gcloud/completion.zsh.inc'; fi
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#
export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

[ -f ~/.gcloud-aliasrc ] && source ~/.gcloud-aliasrc
export GOOGLE_APPLICATION_CREDENTIALS=~/.google-auth/compute-instances.json
export ZSH_DISABLE_COMPFIX=true

export EDITOR="vim"
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

alias dl="cd $HOME/Downloads"
alias dt="cd $HOME/Desktop"
alias localip="ipconfig getifaddr en0"

alias zshconfig="vim $DOTFILE/.zshrc"
alias vimconfig="vim $DOTFILE/.vimrc"
alias vimpluginstall="vim +PluginInstall +qall"
alias sshconfig"vim ~/.ssh/config"
alias reload="source ~/.zshrc"

# Khd alias
alias ctags='`brew --prefix`/bin/ctags'
alias tags='`brew --prefix`/bin/ctags -R .'

# Git alias
alias gpc='git push origin HEAD'
alias gs="git status"

alias todo="todoist --color l"
alias term="export TERM=vt100"


alias ibrew='arch -x86_64 /usr/local/bin/brew'
alias mbrew='arch -arm64e /opt/homebrew/bin/brew'

alias vim="/opt/homebrew/bin/vim"
alias cssh="vim ~/.ssh/config"
alias kssh="kitty +kitten ssh"

alias imgsee="kitty +kitten icat $1"
alias imgsize="file $1"

alias tasks="todoist list"
timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

eval "$(fnm env)"

export DOCKER_DEFAULT_PLATFORM=linux/amd64
export KUBECONFIG=$HOME/.kube/config
